In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import optimize
from scipy.optimize import minimize

# autoreload modules when code is run. Otherwise, python will not see recent changes. 
%load_ext autoreload
%autoreload 2

# We import our project from the py-file
from examproject2 import ProductionEconomyClass

# We import our class
economy = ProductionEconomyClass()

In [2]:
# Question 1
economy.check_market_clearing()

[(0.1, 0.1, True),
 (0.1, 0.31, True),
 (0.1, 0.52, True),
 (0.1, 0.73, True),
 (0.1, 0.94, True),
 (0.1, 1.16, True),
 (0.1, 1.37, True),
 (0.1, 1.58, True),
 (0.1, 1.79, True),
 (0.1, 2.0, True),
 (0.31, 0.1, True),
 (0.31, 0.31, True),
 (0.31, 0.52, True),
 (0.31, 0.73, True),
 (0.31, 0.94, True),
 (0.31, 1.16, True),
 (0.31, 1.37, True),
 (0.31, 1.58, True),
 (0.31, 1.79, True),
 (0.31, 2.0, True),
 (0.52, 0.1, True),
 (0.52, 0.31, True),
 (0.52, 0.52, True),
 (0.52, 0.73, True),
 (0.52, 0.94, True),
 (0.52, 1.16, True),
 (0.52, 1.37, True),
 (0.52, 1.58, True),
 (0.52, 1.79, True),
 (0.52, 2.0, True),
 (0.73, 0.1, True),
 (0.73, 0.31, True),
 (0.73, 0.52, True),
 (0.73, 0.73, True),
 (0.73, 0.94, True),
 (0.73, 1.16, True),
 (0.73, 1.37, True),
 (0.73, 1.58, True),
 (0.73, 1.79, True),
 (0.73, 2.0, True),
 (0.94, 0.1, True),
 (0.94, 0.31, True),
 (0.94, 0.52, True),
 (0.94, 0.73, True),
 (0.94, 0.94, True),
 (0.94, 1.16, True),
 (0.94, 1.37, True),
 (0.94, 1.58, True),
 (0.94, 1.7

In [3]:
# Question 2
economy.find_equilibrium_prices()

economy.consumption_without_tax()

Equilibrium prices: p1 = 0.1, p2 = 0.1
Consumption of c1 without tax: 3.0100082623548494
Consumption of c2 without tax: 7.0233526121613155


(3.0100082623548494, 7.0233526121613155)

In [4]:
# Question 3
economy.find_optimal_tax()

Consumption of c1 with tax: 4.252734422354221
Consumption of c2 with tax: 4.196140919710044
Optimal tax rate: 0.13648030834433636
Social welfare: 0.8705733956305708


(4.252734422354221, 4.196140919710044, 0.13648030834433636, 0.8705733956305708)

In [5]:
# In your Jupyter notebook

from examproject2 import CareerChoiceSimulation  # Import the class

# Create an instance of CareerChoiceSimulation
simulator = CareerChoiceSimulation()

# Perform simulation and get results
overall_expected_utilities, overall_avg_realized_utilities = simulator.simulate_utility()

# Print results
J = 3  # Number of career tracks

print("Overall Expected Utilities:")
for j in range(J):
    display(f"Career {j+1}: {overall_expected_utilities[j]}")

print("\nOverall Average Realized Utilities:")
for j in range(J):
    display(f"Career {j+1}: {overall_avg_realized_utilities[j]}")

Overall Expected Utilities:


'Career 1: 1.0'

'Career 2: 2.0'

'Career 3: 3.0'


Overall Average Realized Utilities:


'Career 1: 0.9929411936957696'

'Career 2: 1.9953572687643204'

'Career 3: 2.9856251271875855'

In [6]:
# In your Jupyter notebook

from examproject2 import CareerChoiceSimulation  # Import the class

# Create an instance of CareerChoiceSimulation
simulator = CareerChoiceSimulation()

# Perform simulation and get results
chosen_careers, prior_expected_utilities, realized_utilities = simulator.simulate_career_choice()

# Print or display the results
print("Chosen Careers:")
display(chosen_careers)

print("\nPrior Expected Utilities:")
display(prior_expected_utilities)

print("\nRealized Utilities:")
display(realized_utilities)

Chosen Careers:


array([1, 1, 2, 0, 2, 2, 2, 2, 2, 2])


Prior Expected Utilities:


array([[0.97625921, 1.99599454, 2.99013847],
       [1.00621717, 1.96877224, 2.98127879],
       [0.98904409, 1.98760038, 2.99863269],
       [1.00788888, 1.99933071, 2.99356056],
       [1.01743697, 2.00041817, 3.00037373],
       [1.0085138 , 2.00141701, 3.01576387],
       [1.00662744, 1.99077093, 2.98809946],
       [0.98008556, 1.98829911, 3.00559389],
       [1.00749867, 2.00686094, 3.00363326],
       [1.0134538 , 2.00660435, 2.9907617 ]])


Realized Utilities:


array([1.98907855, 2.01737148, 2.9901993 , 0.95846943, 2.96377314,
       2.98985232, 3.00737216, 2.95802344, 3.00019509, 3.02306308])

In [7]:
# Assume you have already imported CareerChoiceSimulation and required libraries

# Create an instance of the simulation
sim = CareerChoiceSimulation(N=10)

# Question 1: Simulate and calculate expected utility and the average realized utility for each career choice
expected_utilities, average_realized_utilities = sim.simulate_utility()
print("Expected Utilities: ", expected_utilities)
print("Average Realized Utilities: ", average_realized_utilities)

# Question 2: For each type of graduate, simulate and visualize the share of graduates choosing each career, 
# the average subjective expected utility, and the average ex post realized utility given their choice.
chosen_careers, prior_expected_utilities, realized_utilities = sim.simulate_career_choice()

# Visualization and further processing here
# This can include histograms, bar charts, or line graphs to represent the data effectively


Expected Utilities:  [1. 2. 3.]
Average Realized Utilities:  [0.99294119 1.99535727 2.98562513]


In [8]:

# Initialize the simulation
sim = CareerChoiceSimulation(N=100)

# Run the simulation to get chosen_careers, prior_expected_utilities, and realized_utilities
chosen_careers, prior_expected_utilities, realized_utilities = sim.simulate_career_choice()

# Analyze the results
career_shares, average_prior_utilities, average_realized_utilities, utility_differences = sim.analyze_results(
    chosen_careers, prior_expected_utilities, realized_utilities)

# Print the results
print("Career Shares:", career_shares)
print("Average Prior Expected Utilities:", average_prior_utilities)
print("Average Realized Utilities:", average_realized_utilities)
print("Utility Differences (Realized - Prior):", utility_differences)

# Plotting the results
fig, ax = plt.subplots(4, 1, figsize=(10, 20))

# Plot 1: Share of Graduates Choosing Each Career
ax[0].bar(range(1, sim.par.J + 1), career_shares)
ax[0].set_title('Share of Graduates Choosing Each Career')
ax[0].set_xlabel('Career')
ax[0].set_ylabel('Share')
ax[0].set_xticks(range(1, sim.par.J + 1))
ax[0].set_xticklabels(range(1, sim.par.J + 1))


# Plot 2: Average Prior Expected Utilities
ax[1].bar(range(1, sim.par.J + 1), average_prior_utilities)
ax[1].set_title('Average Prior Expected Utilities')
ax[1].set_xlabel('Career')
ax[1].set_ylabel('Utility')
ax[1].set_xticks(range(1, sim.par.J + 1))
ax[1].set_xticklabels(range(1, sim.par.J + 1))


# Plot 3: Average Realized Utilities
ax[2].bar(range(1, sim.par.J + 1), average_realized_utilities)
ax[2].set_title('Average Realized Utilities After Choosing a Career')
ax[2].set_xlabel('Career')
ax[2].set_ylabel('Utility')
ax[2].set_xticks(range(1, sim.par.J + 1))
ax[2].set_xticklabels(range(1, sim.par.J + 1))


# Plot 4: Utility Differences
ax[3].bar(range(1, sim.par.J + 1), utility_differences)
ax[3].set_title('Utility Differences (Realized - Prior)')
ax[3].set_xlabel('Career')
ax[3].set_ylabel('Utility Difference')
ax[3].set_xticks(range(1, sim.par.J + 1))
ax[3].set_xticklabels(range(1, sim.par.J + 1))


plt.tight_layout()
plt.show()

SyntaxError: invalid syntax (2457319017.py, line 24)

In [ ]:
# Import the necessary class
import matplotlib.pyplot as plt
import numpy as np

# Initialize the simulation
sim = CareerChoiceSimulation(N=10)

# Run the simulation for the initial career choices
chosen_careers, prior_expected_utilities, realized_utilities = sim.simulate_initial_choice()

# Run the simulation for the career switch
new_chosen_careers, new_prior_expected_utilities, new_realized_utilities, switched_careers = sim.simulate_career_switch(chosen_careers, realized_utilities)

# Calculate the share of graduates that chose to switch careers
switch_share = np.mean(switched_careers)

# Print the results
print("Share of graduates that chose to switch careers:", switch_share)
#print the share of graduates that chose to switch careers by previous career
for j in range(sim.par.J):
    switch_share_j = np.mean(switched_careers[chosen_careers == j])
    print(f"Share of graduates from career {j+1} that chose to switch careers:", switch_share_j)

print("New Prior Expected Utilities:", new_prior_expected_utilities)
print("New Realized Utilities:", new_realized_utilities)
print("Switched Careers:", switched_careers)

# Visualize the results
fig, ax = plt.subplots(3, 1, figsize=(10, 15))

# Plot 1: Share of Graduates Choosing to Switch Careers
ax[0].bar(range(1, sim.par.J + 1), [np.mean(switched_careers[chosen_careers == j]) for j in range(sim.par.J)])
ax[0].set_title('Share of Graduates Choosing to Switch Careers')
ax[0].set_xlabel('Initial Career')
ax[0].set_ylabel('Share')
ax[0].set_xticks(range(1, sim.par.J + 1))
ax[0].set_xticklabels(range(1, sim.par.J + 1))


# Plot 2: New Prior Expected Utilities
ax[1].bar(range(1, sim.par.J + 1), np.mean(new_prior_expected_utilities, axis=0))
ax[1].set_title('New Prior Expected Utilities')
ax[1].set_xlabel('Career')
ax[1].set_ylabel('Utility')
ax[1].set_ylim(0, 3)
ax[1].set_xticks(range(1, sim.par.J + 1))
ax[1].set_xticklabels(range(1, sim.par.J + 1))


# Plot 3: New Realized Utilities
ax[2].bar(range(1, sim.par.J + 1), np.mean(new_realized_utilities))
ax[2].set_title('New Realized Utilities After Career Switch')
ax[2].set_xlabel('Career')
ax[2].set_ylabel('Utility')
ax[2].set_xticks(range(1, sim.par.J + 1))
ax[2].set_xticklabels(range(1, sim.par.J + 1))


plt.tight_layout()
plt.show()


In [ ]:
## Problem 3

# Question 1
# Import the class
from examproject2 import BarycentricInterpolation

# Create an instance of the class
interpolator = BarycentricInterpolation()

In [ ]:
interpolator.compute_points()

In [ ]:
interpolator.interpolate()

In [ ]:
# Print the y-coordinates
print(f"y coordinates: ({interpolator.y[0]:.2f}, {interpolator.y[1]:.2f})")

In [ ]:
interpolator.visualize()

In [ ]:
# Interpolate single point
triangle, approx_value = interpolator.interpolate()
true_value = interpolator.func(interpolator.y)
print(f"Triangle: {triangle}, Approximate value: {approx_value:.6f}, True value: {true_value:.6f}")


In [ ]:
# Interpolate a set of points
Y = [(0.2, 0.2), (0.8, 0.2), (0.8, 0.8), (0.2, 0.8), (0.5, 0.5)]
results = interpolator.interpolate_set(Y)